version: '3.8'

services:
    app:
        build: .
        container_name: laravel_app
        restart: always
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
        ports:
            - "8080:8000"
        depends_on:
            db:
                condition: service_healthy
        command: sh -c "
            composer install &&
            php artisan migrate --force &&
            php artisan key:generate &&
            php artisan serve --host=0.0.0.0 --port=8000"
    node:
        image: node:18
        container_name: laravel_node
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
        ports:
            - "5173:5173"
        command: sh -c "npm install && npm run build"
    db:
        image: mysql:8.0
        container_name: laravel_db
        restart: always
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        ports:
            - "3307:3306"
        volumes:
            - db_data:/var/lib/mysql
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            timeout: 5s
            retries: 10

volumes:
    db_data:
